---
title: "MA576 Project: The Geography of Tonal Languages"
author: "Ali Taqi"
date: "May 2nd, 2023"
output: pdf_document
---

```{r setup, include=FALSE}
# Chunk setup
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height = 3, fig.width = 5, fig.align = 'center')
# Load libraries
library(tidyverse)
library(ggnewscale)
library(gt)
library(gtsummary)
library(patchwork)
library(MASS)
library(survival)
library(ggsurvfit)
```

```{r data, include = FALSE}
# Import scripts
source("data.R")
source("humidity.R")
source("plot.R")
source("models.R")
```

# Quantiles

### Coefficient Plot

```{r}
get_q_coefs <- function(q){
  coefs <- summary(get_model_q(q, T))$coefficients[3:5]
  c(bf1 = coefs[1], bf2 = coefs[2], bf3 = coefs[3])
}
```

```{r}
fam_coefs_q <- map_dfr(.x = 1:20, get_q_coefs)
df_fam_coefs_q <- data.frame(q = rep(seq_probs), 
                beta = c(fam_coefs_q$bf1, fam_coefs_q$bf2, fam_coefs_q$bf3), 
                family = c(rep("Austro-Asiatic",20), 
                           rep("Austronesian",20), 
                           rep("Trans-New Guinea",20)))
df_sum_q <- df_fam_coefs_q %>% group_by(q) %>% summarize(sum_q = sum(beta))
sum_rows <- data.frame(q = seq_probs,
                       beta = (df_sum_q$sum_q)/3,
                       family = rep("Average",20))
df_fam_coefs_q <- rbind(df_fam_coefs_q, sum_rows)
```

```{r}
# Make tonality type factor
df_fam_coefs_q$family <- as.factor(df_fam_coefs_q$family)
# Reorder factors
df_fam_coefs_q$family <- factor(df_fam_coefs_q$family, 
                                levels=c("Austro-Asiatic",
                                         "Austronesian",
                                         "Trans-New Guinea",
                                         "Average"))
# Plot params
PAL_famcoefs <- c("red","blue","green","black")
# Plot
coef_plot_q <- df_fam_coefs_q %>%
  ggplot(mapping = aes(x = q, y = beta, group = family, color = family)) +
  geom_point() +
  geom_line() + ylim(-1.2, -0.95) +
  scale_color_manual(name = "Family", values = PAL_famcoefs)
coef_plot_q
```

### Mean Plot

```{r}
QFM <- function(var, q){
  res <- (tonalQ_df %>% 
            filter(isTransGuinean | isAusAsi | isAustro) %>% 
            group_by(family) %>% 
            summarize(mean_fam = mean( {{ var }} )))
  return(data.frame(q = QI(q), mean = res$mean_fam, fam = res$family))
}
df_QFM <- rbind(QFM(Q1, 1), QFM(Q2, 2), QFM(Q3, 3), QFM(Q4, 4),
      QFM(Q5, 5), QFM(Q6, 6), QFM(Q7, 7), QFM(Q8, 8),
      QFM(Q9, 9), QFM(Q10, 10), QFM(Q11, 11), QFM(Q12, 12),
      QFM(Q13, 13), QFM(Q14, 14), QFM(Q15, 15), QFM(Q16, 16),
      QFM(Q17, 17), QFM(Q18, 18), QFM(Q19, 19), QFM(Q20, 20))
```

```{r}
mean_plot_q <- df_QFM %>%
  ggplot(mapping = aes(x = q, y = mean, group = fam, color = fam)) +
  geom_point()+
  geom_line() +
  scale_color_manual(name = "Family", values = PAL_famcoefs[1:3])
```


## Final Plot

```{r, fig.height = 5}
mean_plot_q / coef_plot_q #/ sum_plot_q
```